//@version=6

import lucaOttvn/day_levels_lib/16 as day_levels_lib

indicator(
     "3-Candle Gap Zones + Bullish Gap Fibonacci",
     overlay = true,
     max_boxes_count = 500,
     max_lines_count = 500
)

// set how many bars the indicator have to check back in time
lookbackBars = input.int(
     999999,
     "Lookback bars",
     minval = 3
)

// opening window in minutes
openingMinutes = input.int(
     15,
     "Ignore first minutes of day to avoid extreme volatility",
     minval = 0
)

// ------------ DAY MAX AND MIN SECTION ------------

isNewDay = ta.change(time("D")) != 0

levels    = day_levels_lib.getDayLevels(isNewDay)
float dayHigh = levels.dayHigh
float dayLow  = levels.dayLow

plot(dayHigh, "Day Body High", color = color.white, linewidth = 2)
plot(dayLow,  "Day Body Low",  color = color.white,   linewidth = 2)

// ------------------------------------------------


dayStart = time("D")

openingEnd = dayStart + openingMinutes * 60 * 1000

// the candles included in the opening period must be ignored
// check if both the current and the 3rd candle are over the opening period
afterOpeningPeriod =
     time >= openingEnd and
     not na(time[2]) and
     time[2] >= openingEnd

// --- lookback and candle availability ---
// high shadows
c1High = high[2]
c3High = high

// low shadows
c1Low = low[2]
c3Low = low

// - the gap exists
// - the 3rd candle's close breaks the dayHigh
// - the 3rd candle is big enough to be considered
bullishGap =
     afterOpeningPeriod and
     c3Low > c1High and
     high >= dayHigh and
     close - open > 0.1

// check if: 
// - the gap exists
// - the 3rd candle's close breaks the dayLow
// - the 3rd candle is big enough to be considered
bearishGap =
     afterOpeningPeriod and
     c3High < c1Low and
     high <= dayLow and
     open - close > 0.1

// draw bullish gap zone
if bullishGap
    box.new(
         left = bar_index - 2,
         right = bar_index,
         top = c3Low,
         bottom = c1High,
         bgcolor = color.new(color.green, 65),
         border_color = na
    )

// draw bearish gap zone
if bearishGap
    box.new(
         left = bar_index - 2,
         right = bar_index,
         top = c1Low,
         bottom = c3High,
         bgcolor = color.new(color.red, 65),
         border_color = na
    )


// ------------ FIBONACCI SECTION ------------

var bool insideValidGapZone = false

// when as valid gap is encountered and we aren't in a valid gap zone already
if (bullishGap and insideValidGapZone == false)
    insideValidGapZone := true
    
plot(
    insideValidGapZone ? levels.redLine : na,
    "Fibonacci red line",
    color = color.red,
    linewidth = 2,
    style = plot.style_linebr
)

plot(
    insideValidGapZone ? levels.orangeLine : na,
    "Fibonacci orange line",
    color = color.orange,
    linewidth = 2,
    style = plot.style_linebr
)

plot(
    insideValidGapZone ? levels.aquaLine : na,
    "Fibonacci aqua line",
    color = color.aqua,
    linewidth = 2,
    style = plot.style_linebr
)


// ------------ OPERATION SECTION ------------

var float openedPosition = na

if insideValidGapZone and low < levels.orangeLine and na(openedPosition)
    openedPosition := close

    box.new(
        left = bar_index,
        right = bar_index + 100,
        top = levels.orangeLine,
        bottom = levels.orangeLine - (levels.orangeLine * 0.01),
        bgcolor = color.new(color.red, 80),
        border_color = color.red,
        border_width = 1
    )

    box.new(
        left = bar_index,
        right = bar_index + 100,
        top = levels.orangeLine,
        bottom = levels.orangeLine + (levels.orangeLine * 0.01),
        bgcolor = color.new(color.green, 80),
        border_color = color.green,
        border_width = 1
    )


// end of the day resets
if isNewDay
    insideValidGapZone := false
    openedPosition := na