//@version=6

import lucaOttvn/fib_theme/5 as fib_theme
import lucaOttvn/day_levels_lib/16 as day_levels_lib

indicator(
     "3-Candle Gap Zones + Bullish Gap Fibonacci",
     overlay = true,
     max_boxes_count = 500,
     max_lines_count = 500
)

// set how many bars the indicator have to check back in time
lookbackBars = input.int(
     999999,
     "Lookback bars",
     minval = 3
)

// show/hide bullish Fibonacci
showBullishFib = input.bool(
     false,
     "Show Fibonacci for bullish gaps"
)

// tradingView has object limits.
// each Fibonacci structure uses 7 lines and 6 background boxes.
maxFibSets = input.int(
     40,
     "Maximum amount of Fibonacci structures, the oldest one get garbage collected",
     minval = 1,
     maxval = 60
)

// opening window in minutes
openingMinutes = input.int(
     15,
     "Ignore first minutes of day to avoid extreme volatility",
     minval = 0
)


// ------------ DAY MAX AND MIN SECTION ------------

isNewDay = ta.change(time("D")) != 0

levels    = day_levels_lib.getDayLevels(isNewDay)
float dayHigh = levels.dayHigh
float dayLow  = levels.dayLow

plot(dayHigh, "Day Body High", color = color.white, linewidth = 2)
plot(dayLow,  "Day Body Low",  color = color.white,   linewidth = 2)

// ------------------------------------------------


dayStart = time("D")

openingEnd = dayStart + openingMinutes * 60 * 1000

// the candles included in the opening period must be ignored
// check if both the current and the 3rd candle are over the opening period
afterOpeningPeriod =
     time >= openingEnd and
     not na(time[2]) and
     time[2] >= openingEnd

// --- lookback and candle availability ---
inLookback = bar_index >= last_bar_index - lookbackBars + 1
enoughBars = bar_index >= 2

// high shadows
c1High = high[2]
c3High = high

// low shadows
c1Low = low[2]
c3Low = low

// check if: 
// - there are enough candles
// - the current candle is included in the lookback amount of candles to check
// - the first 15 minutes of the day have passed
// these conditions are needed for both the bullish and bearish gaps
generalConditions = enoughBars and inLookback and afterOpeningPeriod 

// - the gap exists
// - the 3rd candle's close breaks the dayHigh
// - the 3rd candle is big enough to be considered
bullishGap =
     generalConditions and
     c3Low > c1High and
     close >= dayHigh and
     close - open > 0.5

// check if: 
// - the gap exists
// - the 3rd candle's close breaks the dayLow
// - the 3rd candle is big enough to be considered
bearishGap =
     generalConditions and
     c3High < c1Low and
     close <= dayLow and
     open - close > 0.5

// draw bullish gap zone
if bullishGap
    box.new(
         left = bar_index - 2,
         right = bar_index,
         top = c3Low,
         bottom = c1High,
         bgcolor = color.new(color.green, 65),
         border_color = na
    )

// draw bearish gap zone
if bearishGap
    box.new(
         left = bar_index - 2,
         right = bar_index,
         top = c1Low,
         bottom = c3High,
         bgcolor = color.new(color.red, 65),
         border_color = na
    )


// ------------ FIBONACCI SECTION ------------

var bool insideValidGapZone = false

// when as valid gap is encountered and we aren't in a valid gap zone already
if (bullishGap and insideValidGapZone == false)
    insideValidGapZone := true

// when the current candle's low touches the red line, stop drawing Fibonacci (operation exit)
if (low < levels.redLine and insideValidGapZone)
    insideValidGapZone := false

// if Fibonacci continues until the end of the day, stop it
if isNewDay
    insideValidGapZone := false
    
plot(
    insideValidGapZone ? levels.redLine : na,
    "Fibonacci red line",
    color = color.red,
    linewidth = 2,
    style = plot.style_linebr
)

plot(
    insideValidGapZone ? levels.orangeLine : na,
    "Fibonacci orange line",
    color = color.orange,
    linewidth = 2,
    style = plot.style_linebr
)

plot(
    insideValidGapZone ? levels.aquaLine : na,
    "Fibonacci aqua line",
    color = color.aqua,
    linewidth = 2,
    style = plot.style_linebr
)