//@version=6
library("day_levels_lib")

export type DayLevels
    float dayLow
    float dayHigh
    float redLine
    float orangeLine
    float aquaLine

export getDayLevels(bool isNewDay) =>
    var float dayLow  = na
    var float dayHigh = na

    // Current candle body boundaries.
    bodyHigh = math.max(open, close)
    bodyLow  = math.min(open, close)

    if isNewDay
        dayLow  := bodyLow
        dayHigh := bodyHigh
    else
        dayLow  := math.min(dayLow, bodyLow)
        dayHigh := math.max(dayHigh, bodyHigh)

    dayHeight = dayHigh - dayLow

    float redLine = dayLow + dayHeight * 0.5
    float orangeLine = dayLow + dayHeight * 0.618
    float aquaLine = dayLow + dayHeight * 0.786

    DayLevels.new(dayLow, dayHigh, redLine, orangeLine, aquaLine)