//@version=6
library("day_levels_lib")


export type DayLevels
    float dayLow
    float dayHigh


export getDayLevels(bool isNewDay) =>
    var float dayLow  = na
    var float dayHigh = na

    // Current candle body boundaries.
    bodyHigh = math.max(open, close)
    bodyLow  = math.min(open, close)

    if isNewDay
        dayLow  := bodyLow
        dayHigh := bodyHigh
    else
        dayLow  := math.min(dayLow, bodyLow)
        dayHigh := math.max(dayHigh, bodyHigh)

    DayLevels.new(dayLow, dayHigh)