// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © lucaOttvn

//@version=6

// @description TODO: add library description here
library("fib_theme", overlay = true)

export const color fibColor0 = color.white

export const color fibColor0500 = color.red

export const color fibColor0618 = color.orange

export const color fibColor0786 = color.aqua

export const color fibColor1000 = color.white

export const color fibColor1272 = #2a642d

export const color fibColor1618 = color.green


// --- Fibonacci background colors ---
export const color fibFill0To0500 = color.new(color.red, 0)

export const color fibFill0500To0618 = color.new(color.orange, 0)

export const color fibFill0618To0786 = color.new(color.aqua, 0)

export const color fibFill0786To1000 = color.new(color.gray, 0)

export const color fibFill1000To1272 = color.new(#2a642d, 0)

export const color fibFill1272To1618 = color.new(color.green, 0)
